project_name: chores

before:

  hooks:
    - go mod download

builds:
  - binary: chores
    flags:
      - -tags=prod
    main: ./cmd/chores/main.go
    env:
      - CGO_ENABLED=1
    ldflags:
      - -w
      - -s
      - -extldflags '-static'
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: zip
    files:
      - LICENSE
      - README*
      - CHANGELOG*
      - templates
      - static

checksum:
  name_template: 'checksums.txt'

signs:
  - signature: "${artifact}_sig"
    artifacts: all

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^assets:'

release:
  github:
    owner: ngerakines
    name: chores